### ISSUE TITLE
Unable to load since latest world update

### ISSUE THREAD

**Issue by andrewcharlwood** [Th3C0D3R/FoBJS_Release#24]
The Th3C0D3R, hope you're well.

World en5 recently got updated (around 1-2 hours ago), anyway, the bot will not load now past 

"Caching ForgeHX-27df3b6c.js
ForgeHX-27df3b6c.js cached"

Deleted all data but the same issue persisted after, I would assume the secret key has changed with the latest update?

Cheers,

AC

**Comment by Th3C0D3R** [comment]
Can you delete the entire folder in the %appdata% folder and remove the forgeHX file and try again?

**Comment by TemhAAhmeT** [comment]
That doesnt work. Just stuck after caches ForgeHX***.

**Comment by Th3C0D3R** [comment]
Can you create a pullrequest with the cached ForgeHX as a file attached? I have to look into it

**Comment by don-andruha** [comment]
I have the same problem.

> Can you create a pullrequest with the cached ForgeHX as a file attached? I have to look into it

Here you are:
[ForgeHX-1c21bdd3.zip](https://github.com/Th3C0D3R/FoBJS_Release/files/4552654/ForgeHX-1c21bdd3.zip)

**Comment by Th3C0D3R** [comment]
I could locate the issue and I facepalmed my self for not thinking of it. Its because the version number is now 1.177. I only look for a expression like x.xxx.xxx so with two dots and 3 numbers which will cause a problem with the current version. I will create a new version with only this changed.

Maybe its up within the next hour

**Comment by TemhAAhmeT** [comment]
Great :D. Thanks for your time

**Comment by Th3C0D3R** [comment]
Should be fixed with v1.2.4.
Please open a new issue if there is any further issue with the bot
