### ISSUE TITLE
After logging in and selecting world (en8) just blank screen

### ISSUE THREAD

**Issue by vanjavk** [Th3C0D3R/FoBJS_Release#37]
https://i.imgur.com/wiz0POW.png

**Comment by leo899** [comment]
Caching ForgeHX-b56af3c7.js
ForgeHX-b56af3c7.js cached
Loading Bot...

I cleaned everything in appdata, does not help

**Comment by Th3C0D3R** [comment]
strange.... delete the ForgeHX and the foler called "Forge of Bots JS" inside the Roaming folder inside the appdata folder because for me its working before and after that

**Comment by TemhAAhmeT** [comment]
same for me too,
even deleting everything doesnt help.

**Comment by Th3C0D3R** [comment]
please try to use the "Delete every Data" button in the settings menu (if not tried) because everything is working for me

**Comment by vanjavk** [comment]
I deleted "Forge of Bots JS" inside the Roaming folder,but I don't have ForgeHX folder.
![image](https://user-images.githubusercontent.com/1491765/87785993-7764b080-c839-11ea-934b-d0ccc78063d5.png)
![image](https://user-images.githubusercontent.com/1491765/87786012-80558200-c839-11ea-9fc7-d4c87a64d6cf.png)
![image](https://user-images.githubusercontent.com/1491765/87786025-89deea00-c839-11ea-8418-c9f12500ed1d.png)
now little delay 5 seconds
![image](https://user-images.githubusercontent.com/1491765/87786051-9b27f680-c839-11ea-85de-6b1a4eb6373d.png)
Now it's not blank screen, it shows what other user has said:
![image](https://user-images.githubusercontent.com/1491765/87786140-b85cc500-c839-11ea-96cb-6aba7394b992.png)
but still stucks on Loading bot...

If I close and just restart I get just Loading bot...
![image](https://user-images.githubusercontent.com/1491765/87786358-18536b80-c83a-11ea-9db8-0ea7a4789d20.png)

If I do delete data from Settings I get blank screen again:
![image](https://user-images.githubusercontent.com/1491765/87786478-446eec80-c83a-11ea-947d-872f19849d7c.png)

**Comment by TemhAAhmeT** [comment]
I also deleted every folder at first and after used "Delete every Data" as you suggested. result is same as vanjavk..

**Comment by Th3C0D3R** [comment]
ok i see the problem... wait i will do something for all of you ;)

**Comment by Th3C0D3R** [comment]
https://github.com/Th3C0D3R/FoBJS/

have fun ;) will accept PR if they are tested and working or new features

**Comment by Th3C0D3R** [comment]
also its working again but have to build ur own

**Comment by vanjavk** [comment]
I can confirm it works now! thanks

**Comment by 4vizz** [comment]
I have same situation as @vanjavk while using repo that u linked here, just black screen after entering login, password, picking server. When I'm using "official" release it stucks at Loading Bot. Cleaning mentioned folders also doesn't help
•pl9
•Windows 10 64 bit
•No errors
•Launching
•Not launching

**Comment by vanjavk** [comment]
> I have same situation as @vanjavk while using repo that u linked here, just black screen after entering login, password, picking server. When I'm using "official" release it stucks at Loading Bot. Cleaning mentioned folders also doesn't help
> •pl9
> •Windows 10 64 bit
> •No errors
> •Launching
> •Not launching

Use
`git reset --hard 694351704c47010b83726d84caaa73664a6795b2`
then
`npm install`

and then delete everything in appdata and it should work

**Comment by 4vizz** [comment]
> I have same situation as @vanjavk while using repo that u linked here, just black screen after entering login, password, picking server. When I'm using "official" release it stucks at Loading Bot. Cleaning mentioned folders also doesn't help
> •pl9
> •Windows 10 64 bit
> •**No errors**
> •Launching
> •Not launching

Sorry, my bad, I'm actually getting an error that I haven't seen beforce because I compiled it instead running from the source. Here it's:

> [DEBUG] WID (pl9) loaded
(node:12856) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at C:\Users\Avizz\Desktop\FoE\module\FoBProxy.js:60:36
(node:12856) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at C:\Users\Avizz\Desktop\FoE\module\FoBProxy.js:60:36
(node:12856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't know if it's important but while installing nodes I had to use:
`npm install --save-dev electron-packager@15.0.0`
`npm update asar --depth 2`
`npm update minimist --depth 3`
in order to fix 3 low severity vulnerabilities in 217 scanned packages

**Comment by vanjavk** [comment]
I dont know but it could be, try without it, just ignore vulnerabilities

**Comment by Th3C0D3R** [comment]
Vuls don't matter because its not a server or something like that so just use the package.config and all Version mentioned in it

**Comment by 4vizz** [comment]
Ignoring those vuls didn't help at all, still same thing is happening. I downloaded fresh repo right before writing this comment so it's up to date. But it's something with my pc I guess, if no1 else is having these problems, so don't bother fixing it just for me

**Comment by vanjavk** [comment]
> Ignoring those vuls didn't help at all, still same thing is happening. I downloaded fresh repo right before writing this comment so it's up to date. But it's something with my pc I guess, if no1 else is having these problems, so don't bother fixing it just for me

I told you in my comment to grab certain commit and not fresh repo, newest repo doesnt work for me either

**Comment by BreimmGer** [comment]
Hello
who could please help me to set up bot with the new version.

thank you
