### ISSUE TITLE
Auto Production Bot

### ISSUE THREAD

**Issue by TemhAAhmeT** [Th3C0D3R/FoBJS_Release#6]
Server: en
Os: Windows
No errors on screen

I am expecting the production bot collect gold and supplies when they are done.

But bot just waits when collecting supplies and golds are possible. When i click manually to ""Collect Production" it works and collects them all and restarts production. But not doing it automatically.

**Comment by Th3C0D3R** [comment]
Like I said in the changelog:
`Bots: Currently the Bot is under development. Currently, if you activate him, he will start new production as soon as you collect them. I am on it to fix the problems I have with a working bot.`

So the Bot only starts production after collecting them automatically if active.
But as I am writing this comment, an Idea got into my mind and maybe its not that hard to fix it.
I had to remove it because it produced high CPU and Memory Usage, but now 🤔 

Its fixed with the next release (which is coming out tomorrow

**Comment by TemhAAhmeT** [comment]
Ah, sorry. I understood slightly different.
Anyway, thanks for the good news 💃 
Have a nice day.
